[package]
name = "wyndow"
version = "0.0.1-dev"
edition = "2024"
license = "MIT"

[dependencies]
libc = { version = "0.2.172" }
winapi = { version = "0.3.9", features = [ "windef", "wingdi", "libloaderapi", "winuser", "minwindef"] }
thiserror = { version = "2.0.12"  }